# Generated by Django 5.2.8 on 2026-07-04 18:49

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_campaign_name_ci'),
        ),
    ]
