# Generated by Django 5.2.8 on 2026-07-04 22:46

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_unique_campaign_name_ci'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='campaign',
            name='unique_campaign_name_ci',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_campaign_name_ci', violation_error_message='A campaign with this name already exists.'),
        ),
    ]
